/*
 SPDX-License-Identifier: AGPL-3.0-or-later

 Copyright (C) 2025 - 2026 emexlab

 This file is part of Nyxian.

 Nyxian is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Nyxian is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with Nyxian. If not, see <https://www.gnu.org/licenses/>.
*/

#include "Broadpatch.h"

/* libc API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(open);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(close);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(dup);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(dup2);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fcntl);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(realpath);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(openat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(__close_nocancel);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(__open_nocancel);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(read);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(write);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(pread);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(pwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(readv);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(writev);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(lseek);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(stat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(stat64);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(lstat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fstat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fstatat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(access);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(faccessat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(unlink);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(unlinkat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(rename);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(renameat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(link);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(symlink);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(symlinkat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(readlink);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(readlinkat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mkdir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mkdirat);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(rmdir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(chdir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fchdir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getcwd);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(opendir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(readdir);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getdirentries);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getattrlist);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getattrlistbulk);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(chmod);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fchmod);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(chown);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fchown);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(chflags);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(truncate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(ftruncate);

/* task API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_get_special_port);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_set_special_port);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_ports_lookup);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_ports_register);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(host_get_special_port);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(host_self_trap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_host_self);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_task_self);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_threads);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_suspend);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_resume);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_terminate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(bootstrap_look_up);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(bootstrap_look_up2);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(bootstrap_register);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(bootstrap_check_in);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_make_memory_entry);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_make_memory_entry_64);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_for_pid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_name_for_pid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_read_for_pid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(task_inspect_for_pid);

/* mmap API  */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mmap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(munmap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mprotect);

/* mach VM API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_protect);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_inherit);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_map);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_remap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read_list);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_read_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_write);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_copy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_wire);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_msync);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_behavior_set);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_machine_attribute);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_purgable_control);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_region);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_region_recurse);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_query);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_vm_page_range_query);

/* legacy VM API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_protect);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_inherit);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_map);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_remap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read_list);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_read_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_write);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_copy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_wire);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_msync);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_behavior_set);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_machine_attribute);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_purgable_control);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_region_64);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(vm_region_recurse_64);

/* mach port API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_deallocate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_construct);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_extract_right);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_names);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_type);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_rename);               /* deprecated */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_name);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_qos);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_allocate_full);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_destroy);              /* deprecated */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_destruct);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_refs);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_mod_refs);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_insert_right);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_srights);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_peek);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_mscount);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_seqno);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_request_notification);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_set_status);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_move_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_insert_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_extract_member);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_attributes);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_attributes);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_get_context);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_set_context);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_guard);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_unguard);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_space_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_space_basic_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_dnrequest_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_port_kernel_object);

/* mach messaging API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_overwrite);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_trap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_overwrite_trap);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_receive);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_send);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_destroy);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server_once);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(mach_msg_server_importance);

/* fileport API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fileport_makeport);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(fileport_makefd);

/* dyld API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(dlopen);

/* ioctl API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(ioctl);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(isatty);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(tcgetattr);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(tcsetattr);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(tcsetpgrp);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(tcgetpgrp);

/* libproc API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(__proc_info);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_pidinfo);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_name);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_pidpath);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_listallpids);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_pid_rusage);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(proc_kmsgbuf);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(kill);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(raise);

/* mount API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getmntinfo);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getmntinfo_r_np);

/* SecItem API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecItemAdd);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecItemCopyMatching);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecItemUpdate);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecItemDelete);

/* sysctl API */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(sysctl);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(sysctlbyname);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(gethostname);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(sethostname);

/* ucred APIs */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getuid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getgid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(geteuid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getegid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getpid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getppid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setuid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(seteuid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setruid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setreuid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setgid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setegid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setrgid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setregid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(getsid);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(setsid);

/* code-signing / process trust queries */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(csops);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(csops_audittoken);

/* Security.framework task/entitlement queries */
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecTaskCreateFromSelf);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecTaskCreateWithAuditToken);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecTaskCopyValueForEntitlement);
LIBKERN_DEFINE_INTERPOSE_PATCHABLE(SecTaskCopyValuesForEntitlements);
